---
- name: Install deploy packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - aptitude
    - build-essential
    - git
    - ntp
    - ntpdate
    - openssh-server
    - python-dev
    - sudo
    - tmux
    - bridge-utils
    
- name: Configure NTP
  copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
  notify: ntp

- name: Create root ssh folder
  file: path=/root/.ssh/ owner=root group=root state=directory mode=0755 

- name: Deploy private ssh key
  copy: src=id_rsa dest=/root/.ssh/id_rsa owner=root group=root mode=0600

- name: Deploy public ssh key
  copy: src=id_rsa.pub dest=/root/.ssh/id_rsa.pub owner=root group=root mode=0644

- name: Configure interfaces
  template: src=interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
  notify: networking
  
- name: Clone Openstack Ansible repo
  git: repo=https://github.com/openstack/openstack-ansible.git
       dest=/opt/openstack-ansible/
       version={{ osa_version }}

- name: Run Openstack Ansible
  command: scripts/bootstrap-ansible.sh
  args:
    chdir: /opt/openstack-ansible
    creates: /opt/ansible_*

- name: Copy Openstack Ansible base configuration
  command: cp -r /opt/openstack-ansible/etc/openstack_deploy /etc/openstack_deploy
  args:
    creates: /etc/openstack_deploy

- name: Copy Openstack Ansible configuration
  copy: src=openstack_user_config.yml dest=/etc/openstack_deploy/openstack_user_config.yml owner=root group=root mode=0644

- name: Copy Openstack Ansible user variables
  copy: src=user_variables.yml dest=/etc/openstack_deploy/user_variables.yml owner=root group=root mode=0644
