---
- name: Copy TFTP Xinetd Config
  copy: src=tftp dest=/etc/xinetd.d/tftp owner=root group=root mode=0640
  notify:
    - xinetd

- name: Check CentOS Repo Directory
  stat: path=/var/pxe/centos7
  register: repo

- name: Make CentOS Repo Directory
  file: path=/var/pxe/centos7 state=directory owner=root group=root mode=0644
  when: not repo.stat.exists

- name: Make CentOS TFTP Directory
  file: path=/var/lib/tftpboot/centos7 state=directory owner=root group=root mode=0644
  notify:
    - tftp

- name: Make CentOS ISO Directory
  file: path=/opt/centos/iso state=directory owner=root group=root mode=0644

- name: Make CentOS Kickstart Directory
  file: path=/opt/centos/kickstart state=directory owner=root group=root mode=0644

- name: Stat CentOS Iso
  stat: path=/opt/centos/iso/centos.iso
  register: iso

- name: Download CentOS Iso
  get_url: url=http://dallas.tx.mirror.xygenhosting.com/CentOS/7/isos/x86_64/CentOS-7-x86_64-DVD-1511.iso dest=/opt/centos/iso/centos.iso owner=root group=root mode=0644
  when: not iso.stat.exists

- name: Copy CentOS Kickstart
  copy: src=node.ks dest=/opt/centos/kickstart/node.ks owner=root group=root mode=0644

- name: Copy httpd Virtual Host PXE Boot
  copy: src=httpd-pxeboot.conf dest=/etc/httpd/conf.d/pxeboot.conf owner=root group=root mode=0644
  notify:
    - httpd

- name: Copy httpd Virtual Host Kickstart
  copy: src=httpd-kickstart.conf dest=/etc/httpd/conf.d/kickstart.conf owner=root group=root mode=0644
  notify:
    - httpd

- name: Copy default
  copy: src=menu-default dest=/var/lib/tftpboot/pxelinux.cfg/default owner=root group=root mode=0644
  notify:
    - tftp

- name: Update fstab
  lineinfile: dest=/etc/fstab state=present line="/opt/centos/iso/centos.iso	/var/pxe/centos7	iso9660	ro	0	0"
  notify:
    - fstab

- name: Copy vmlinuz
  command: cp /var/pxe/centos7/images/pxeboot/vmlinuz /var/lib/tftpboot/centos7/
  notify:
    - tftp

- name: Copy initrd.img
  command: cp /var/pxe/centos7/images/pxeboot/initrd.img /var/lib/tftpboot/centos7/ 
  notify:
    - tftp

- name: Copy pxelinux.0
  command: cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot/
  notify:
    - tftp

- name: Copy menu.c32
  command: cp /usr/share/syslinux/menu.c32 /var/lib/tftpboot/
  notify:
    - tftp

- name: Copy memdisk
  command: cp /usr/share/syslinux/memdisk /var/lib/tftpboot/
  notify:
    - tftp

- name: Copy mboot.c32
  command: cp /usr/share/syslinux/mboot.c32 /var/lib/tftpboot/
  notify:
    - tftp
    
- name: Copy chain.c32
  command: cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot/
  notify:
    - tftp

- name: Add ip_conntrack_tftp
  lineinfile: dest=/etc/modprobe.d/tftp.conf line="nf_conntrack_tftp" create=yes

- name: Enable TFTP
  service: name=tftp enabled=yes

- name: Start TFTP
  service: name=tftp state=started

- name: Enable Xinetd
  service: name=xinetd enabled=yes

- name: Start Xinetd
  service: name=xinetd state=started

- name: Enable httpd
  service: name=httpd enabled=yes

- name: Start httpd
  service: name=httpd state=started

