---
- name: Update base system
  apt: upgrade=dist update_cache=yes

- name: Install deploy packages
  apt: name={{ item }} state=present
  with_items:
    - bridge-utils
    - debootstrap
    - ifenslave
    - ifenslave-2.6
    - lsof
    - lvm2
    - ntp
    - ntpdate
    - openssh-server
    - sudo
    - tcpdump
    - vlan

- name: Create root ssh folder
  file: path=/root/.ssh/ owner=root group=root state=directory mode=0755

- name: Add deployment host public key
  authorized_key: user=root key="{{ item }}" state=present exclusive=yes
  with_file:
    - id_rsa.pub

- name: Configure NTP
  copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
  notify: ntp
